[package]
name = "ion-mail"
version = "0.2.1"
edition = "2024"
description = "A simple mail CLI"
authors = ["Paul8711 <support@paul8711.com>"]
license = "AGPL-3.0-only"
repository = "https://github.com/paul8711-code/ion-mail"

[package.metadata.wix]
upgrade-guid = "E939105E-8B38-4C78-80D6-65E9FB114071"
path-guid = "017A142D-3D40-45FD-8FF2-C54C1A05F96C"
license = false
eula = false

[dependencies]
chrono = "0.4.44"
clap = { version = "4.6.0", features = ["derive"] }
dialoguer = "0.12.0"
dirs = "6.0.0"
email_address = "0.2.9"
html2md = "0.2.15"
imap = "2.4.1"
keyring-core = "1.0.0"
lettre = "0.11.21"
mailparse = "0.16.1"
markdown = "1.0.0"
mime_guess = "2.0.5"
minus = { version = "5.6.1", features = ["dynamic_output"] }
native-tls = "0.2.18"
oauth2 = { version = "5.0.0", features = ["reqwest-blocking"] }
reqwest = { version = "0.13.3", features = ["blocking"] }
serde = "1.0.228"
serde_json = "1.0.150"
shellexpand = "3.1.2"
strip_markdown = "0.2.0"
termimad = "0.34.1"
toml = "1.1.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = "1.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
zbus-secret-service-keyring-store = { version = "1.0.0", features = ["crypto-rust"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
