name: Add Provider
description: Add a new Oauth2 provider.
title: "Add Provider: "
labels: ["provider-request"]
assignees:
  - Paulprojects8711
body:
  - type: input
    id: provider
    attributes:
      label: Provider
      description: Email provider you would like to request
      placeholder: ex. gmail.com
    validations:
      required: true
  - type: input
    id: smtp-host
    attributes:
      label: SMTP Host
      description: SMTP Host of the provider
      placeholder: ex. smtp.example.com
    validations:
      required: true
  - type: input
    id: smtp-port
    attributes:
      label: SMTP Port
      description: SMTP Port of the provider
      placeholder: ex. 465
    validations:
      required: true
  - type: dropdown
    id: smtp-security
    attributes:
      label: SMTP Security
      description: Encryption method used by the provider
      options:
        - SSL
        - STARTTLS
      default: 0
    validations:
      required: true
  - type: input
    id: imap-host
    attributes:
      label: IMAP Host
      description: IMAP Host of the provider
      placeholder: ex. imap.example.com
    validations:
      required: true
  - type: input
    id: imap-port
    attributes:
      label: IMAP Port
      description: IMAP Port of the provider
      placeholder: ex. 993
    validations:
      required: true
  - type: dropdown
    id: imap-security
    attributes:
      label: IMAP Security
      description: Encryption method used by the provider
      options:
        - SSL
        - STARTTLS
      default: 0
    validations:
      required: true
  - type: input
    id: oidc
    attributes:
      label: OIDC Discovery Endpoint
      description: Link to the OIDC Discovery Endpoint of the provider
      placeholder: ex. https://accounts.google.com/.well-known/openid-configuration
    validations:
      required: true
  - type: textarea
    id: scopes
    attributes:
      label: Scopes
      description: Permissions ion-mail needs to use the provider (separated by newlines)
      placeholder: ex. openid
    validations:
      required: true
